# Bu araÃ§ @keyiflerolsun tarafÄ±ndan | @KekikAkademi iÃ§in yazÄ±lmÄ±ÅŸtÄ±r.

name: Domain DeÄŸiÅŸiklik KontrolÃ¼

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: 00 21 * * *

jobs:
  DomainKontrol:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name : Depo KontrolÃ¼
        uses : actions/checkout@v4

      - name : Python 3.11.8 YÃ¼kle
        uses : actions/setup-python@v5
        with :
          python-version: 3.11.8

      - name : Python SÃ¼rÃ¼mÃ¼nÃ¼ GÃ¶ster
        run  : python -c "import sys; print(sys.version)"

      - name : Gereksinimleri YÃ¼kle
        run  : |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik cloudscraper

      - name : BetiÄŸi Ã‡alÄ±ÅŸtÄ±r
        run  : |
          python KONTROL.py

      - name : DeÄŸiÅŸiklik KontrolÃ¼
        id   : degisiklik_kontrol
        run  : |
          git diff --quiet . || echo "degisiklik=true" >> $GITHUB_OUTPUT

      - name : Pull Request OluÅŸtur
        if   : steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run  : |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit --author="keyiflerolsun <keyiflerolsun@users.noreply.github.com>" \
            -m "â™»ï¸ Domain DeÄŸiÅŸikliÄŸi" \
            -m "ğŸ”„ Otomatik domain gÃ¼ncellemeleri yapÄ±ldÄ±."
          BRANCH="domain-degisiklik-$(date +%s)"
          git checkout -b $BRANCH
          git push origin $BRANCH
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls \
            -d @- <<EOF
          {
            "title": "â™»ï¸ Domain DeÄŸiÅŸikliÄŸi",
            "head": "$BRANCH",
            "base": "master",
            "body": "ğŸ”„ Otomatik tespit edilen domain deÄŸiÅŸiklikleri uygulandÄ±.\n\nğŸ“‚ Ä°lgili dosyalar gÃ¼ncellendi. LÃ¼tfen deÄŸiÅŸiklikleri gÃ¶zden geÃ§irin ve onaylayÄ±n."
          }
          EOF
